version: '2'

services:

  intellij:
    image: sebmoule/docker-intellij
    environment:
      - "DISPLAY=${DISPLAY}"
    hostname: intellij
    tty: true
    stdin_open: true
    network_mode: host 
    volumes:
      - ${HOME}:/home/developer
      - /mnt/filer/work:/mnt/filer/work
      - /tmp/.X11-unix:/tmp/.X11-unix




#      - ${HOME}/.Xauthority:/home/developer/.Xauthority
#      - ${HOME}/.IdeaIC2016.1:/root/.IdeaIC2016.1
#      - ${HOME}/IdeaProjects:/root/IdeaProjects

